### PR TITLE
feat: Private repo support

### LINKED ISSUE #1: Support private repos
This extension looks great! However, I mostly work on private repos, so maybe I can contribute to make it work.

What is different in private repos which makes you disable the extensions for them?

### PR DESCRIPTION
**Pull request by bentleyvk**
It should support private repos now.
Main `content.js` script waits until `token-extractor.js` script in iframe sends images' URLs with a token and then proceeds to load the comparer.

### CODE REVIEW

**Comment by bentleyvk** [comment]
@bersbersbers could you check whether it works on your private repos?

**Comment by bersbersbers** [comment]
It is working, in principle!

However, it seems to have (timing?) issues in big PRs. I have a big one (90 files - 83 non-image ones which are "viewed", plus 7 non-viewed images) where I get this for the first 4:
image

and this only for the last 3 images:
image

Should I try extending some timeout value to see if that fixes things? If so, which one?

**Comment by bentleyvk** [comment]
Hm, maybe try adding `console.log` to `token-extractor.js` to check whether it is being called on all image files.

**Comment by bersbersbers** [comment]
Tried that. I get 8 URLs sent quickly (the ones that are missing, I guess), and then 6 more 2-3 seconds later (the working ones). It sounds like the first 8 are sending too early. Reminds me of https://github.com/bentleyvk/github-pr-image-comparer/issues/1#issuecomment-1149099788:

> **The difficult part is to make sure that `content.js` has fully loaded when `src_extractor.js` starts sending messages.** In a big PR with hundreds of files, this is hard to guarantee with the naive sleep I use above. I don't know about the order of processing with `iframe`s, but if it were guaranteed that the `iframe`s are all loaded before the main page, `src_extractor.js` could simply wait for a single message from `content.js`.

**Comment by bentleyvk** [comment]
I guess then I need to make some messaging mechanism to workaround different script and iframes loading times.

**Comment by bentleyvk** [comment]
@bersbersbers I added messaging mechanism as I was saying. While testing, I also saw that iframes post messages even before my content script starts listening.

**Comment by bersbersbers** [comment]
Awesome - works great, thanks a lot!

**Comment by bentleyvk** [comment]
Great, thank you for testing this out!

**Pull request merged**
